### ISSUE TITLE
Calling `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by gugahoa** [spacekookie/thunder#16]
Minimal example can be found here, in panic.rs, along with output: https://gist.github.com/gugahoa/25b79588ab566360ef586e57cbef993d

**Comment by gugahoa** [comment]
Updated the gist with panic.rs `cargo expand` result

**Comment by spacekookie** [comment]
Okay so these are kinda two issues. Both need to be addressed but also have very different causes. So I will close this one and open two new ones just so I can track their process better.

Thanks for reporting this :+1:

**Comment by gugahoa** [comment]
No problem!
