### ISSUE TITLE
thunder does not build on 1.29.0-nightly

### ISSUE THREAD

**Issue by lrbalt** [spacekookie/thunder#25]
see thunder's CI-failures.

**Comment by gugahoa** [comment]
Meanwhile, for people looking for a quick solution, you can install nightly-2018-06-27:
`rustup toolchain install nightly-2018-06-27`

**Comment by spacekookie** [comment]
Hey there. I've been on holiday for the last week. Thanks for reporting this. I'll have a look at what's going on next week :wink:

**Comment by gugahoa** [comment]
Thunder is working as expected, this is a nightly bug: https://github.com/rust-lang/rust/issues/52469

**Comment by lrbalt** [comment]
after changing to `#![feature(use_extern_macros)]` everything works again. Thanks @gugahoa
